# Generated by Django 4.2.1 on 2023-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
                ('address', models.CharField(help_text='Enter owner', max_length=20)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=20)),
            ],
        ),
    ]
