# Generated by Django 4.2.1 on 2023-06-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooShop_app', '0002_productype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(help_text='Enter vendor code', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
                ('description', models.TextField(help_text='Enter description')),
                ('cost', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('product_type', models.ForeignKey(help_text='Choose product type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zooShop_app.producttype')),
                ('provider', models.ForeignKey(help_text='Choose provider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zooShop_app.provider')),
            ],
        ),
    ]
